# Generated by Django 2.1.1 on 2018-11-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0002_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='http://www.activesports.gr/content/images/thumbs/default-image_450.png', max_length=200),
            preserve_default=False,
        ),
    ]
